"""Environment preflight: check the route interpreter before anything is launched.

The evaluator imports the agent only after it has started CARLA and waited out the simulator's
start-up, so an interpreter that cannot ``import py_trees`` -- or a bare ``python3`` that the
job's activation resolves to some other environment -- used to cost one simulator start-up per
route to discover, and then surfaced as an infrastructure failure on every route in turn.

This runs ``environment.python`` once, on the host the runner runs on, under the same
activation, ``agent.env``, ``PYTHONPATH`` and working directory a route gets (built by
:func:`oodbench.jobscript.environment_prelude`, never copied), and imports what the evaluator
imports: ``carla``, ``py_trees``, ``numpy``, ``scipy`` and the agent module, the evaluator's
way. Any failure aborts the sweep before the first route. On success the interpreter, the
versions it found and the ``agent.env`` the routes get are written to
``<output.root>/_runner/env_provenance.json``.

Deliberately NOT checked: the GPU, CUDA, or anything the agent does in ``setup()``. Those need
the simulator and the route; this is only the part that can be known for free.
"""

from __future__ import annotations

import json
import os
import shlex
import subprocess
import time
from pathlib import Path
from typing import TYPE_CHECKING, Any, Dict

from .jobscript import environment_prelude

if TYPE_CHECKING:  # pragma: no cover
    import logging

    from .config import Config

SCHEMA = 1

#: (distribution name for ``importlib.metadata``, module name to import), in report order.
PACKAGES = (("numpy", "numpy"), ("scipy", "scipy"), ("carla", "carla"), ("py_trees", "py_trees"))

#: Generous: importing a model's agent module can pull in torch and its extensions.
TIMEOUT_S = 600

MARKER = "OODPB_ENV_PREFLIGHT_RESULT "

#: Runs inside ``environment.python``. Must stay importable by any Python 3 the runner might
#: be pointed at, so: standard library only, and no f-string features newer than 3.6.
_PROBE = r'''
import importlib, json, os, platform, sys, traceback
try:
    from importlib import metadata as _md
except ImportError:  # Python < 3.8
    _md = None

packages, failures = {}, []

def _owned_version(dist, mod):
    # The installed distribution's version, but only if the module that was imported is one of
    # its files: a copy found earlier on the path (a CARLA egg on PYTHONPATH in front of a
    # pip-installed wheel) would otherwise be reported under the wheel's version.
    target = getattr(mod, "__file__", None)
    if _md is None or not target:
        return None
    target = os.path.realpath(target)
    try:
        d = _md.distribution(dist)
        for f in d.files or ():
            if (os.path.basename(str(f)) == os.path.basename(target)
                    and os.path.realpath(str(d.locate_file(f))) == target):
                return d.version
    except Exception:
        pass
    return None

def _version(dist, mod):
    v = _owned_version(dist, mod)
    if v is None:
        v = getattr(mod, "__version__", None)
    return None if v is None else str(v)

for dist, name in json.loads(sys.argv[1]):
    try:
        packages[dist] = _version(dist, importlib.import_module(name))
    except BaseException:
        packages[dist] = None
        failures.append({"what": name, "error": traceback.format_exc(limit=3)})

# The evaluator's own import: its directory is sys.path[0] (it is run as a script), the
# agent's directory is put in front of that, and the module is the file's basename.
agent = sys.argv[2]
sys.path[0] = sys.argv[3]
sys.path.insert(0, os.path.dirname(agent))
agent_ok = True
try:
    importlib.import_module(os.path.basename(agent).split(".")[0])
except BaseException:
    agent_ok = False
    failures.append({"what": "agent " + agent, "error": traceback.format_exc(limit=5)})

print(%(marker)r + json.dumps({
    "python_executable": sys.executable,
    "python_version": platform.python_version(),
    "packages": packages,
    "agent_import_ok": agent_ok,
    "failures": failures,
}), flush=True)
''' % {"marker": MARKER}


class EnvCheckError(RuntimeError):
    """The route interpreter cannot import what the evaluator needs."""


_HINT = ("Fix `environment.python` (give it as an ABSOLUTE path to the interpreter that has "
         "the evaluator's dependencies and your agent's), `environment.activate` or "
         "`agent.pythonpath`, then re-run. --skip-env-preflight bypasses this check; every route "
         "would then fail the same way, after a simulator start-up each.")


def render(cfg: "Config") -> str:
    """The bash source of the preflight: the route's environment, then the probe."""
    argv = [cfg.environment["python"], "-c", _PROBE,
            json.dumps([list(p) for p in PACKAGES]), str(cfg.agent["entrypoint"]),
            str(cfg.evaluator_path.parent)]
    lines = ["#!/bin/bash",
             "# Generated by the OOD-PerceptionBench runner: environment preflight.",
             "# The same activation, agent.env, paths and working directory as a route attempt.",
             "set -o pipefail", ""]
    lines.extend(environment_prelude(cfg))
    lines.append("")
    lines.append(" ".join(shlex.quote(a) for a in argv))
    return "\n".join(lines) + "\n"


def run(cfg: "Config", log: "logging.Logger") -> Dict[str, Any]:
    """Run the preflight, log what it found, write the provenance file and return it.

    Raises :class:`EnvCheckError` on any failure, with the evidence in the message.
    """
    runner_dir = Path(cfg.output["root"]) / "_runner"
    runner_dir.mkdir(parents=True, exist_ok=True)
    script = runner_dir / "env_preflight.sh"
    script.write_text(render(cfg), encoding="utf-8")

    python = cfg.environment["python"]
    log.info("environment preflight: importing carla, py_trees, numpy, scipy and the agent "
             "with %s", python)
    try:
        proc = subprocess.run(["bash", str(script)], stdout=subprocess.PIPE,
                              stderr=subprocess.STDOUT, stdin=subprocess.DEVNULL,
                              timeout=TIMEOUT_S, universal_newlines=True)
    except subprocess.TimeoutExpired:
        raise EnvCheckError(f"environment preflight did not finish within {TIMEOUT_S} s "
                            f"(script: {script}). {_HINT}") from None
    output = proc.stdout or ""
    result = None
    for line in output.splitlines():
        if line.startswith(MARKER):
            result = json.loads(line[len(MARKER):])
    tail = "\n".join(output.splitlines()[-30:])

    if result is None:
        raise EnvCheckError(
            f"environment preflight could not run {python!r} (exit {proc.returncode}; script: "
            f"{script}). Last output:\n{tail}\n{_HINT}")

    log.info("environment preflight: python %s (%s)", result["python_executable"],
             result["python_version"])
    for dist, _ in PACKAGES:
        log.info("environment preflight:   %-9s %s", dist, result["packages"].get(dist))
    if not os.path.isabs(python):
        log.warning("environment.python is %r, not an absolute path; it resolved to %s here. "
                    "Give the absolute path so every host and every route resolves the same "
                    "interpreter.", python, result["python_executable"])

    if result["failures"]:
        detail = "\n".join(f"--- {f['what']}:\n{f['error'].rstrip()}" for f in result["failures"])
        names = ", ".join(f["what"] for f in result["failures"])
        raise EnvCheckError(
            f"environment preflight: {result['python_executable']} cannot import {names}.\n"
            f"{detail}\n{_HINT}")
    if proc.returncode != 0:
        raise EnvCheckError(f"environment preflight exited {proc.returncode} (script: {script})."
                            f" Last output:\n{tail}\n{_HINT}")

    provenance = {
        "schema": SCHEMA,
        "checked_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "python_executable": result["python_executable"],
        "python_version": result["python_version"],
        "packages": {dist: result["packages"].get(dist) for dist, _ in PACKAGES},
        "agent_entrypoint": str(cfg.agent["entrypoint"]),
        "agent_import_ok": bool(result["agent_import_ok"]),
        # As every route receives it (the runner's reserved variables are added per route and
        # are not part of it). The golden builder checks DATAGEN here.
        "agent_env": dict(cfg.agent["env"]),
    }
    path = runner_dir / "env_provenance.json"
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(json.dumps(provenance, indent=2) + "\n", encoding="utf-8")
    os.replace(tmp, path)
    log.info("environment preflight: OK, wrote %s", path)
    return provenance
