"""Per-route bash generation -- the inverted per-route template.

The internal orchestrators generate one of these per route and hand it to a scheduler. Here the
runner owns the loop and the script is a thin, auditable record of exactly what was executed:
one file per (route, seed), regenerated at plan time, never appended to.

Three properties this file must not break, all load-bearing:

1. **No ``setsid``, no ``nohup``, no backgrounding of the python call.** The vendored evaluator
   deliberately does *not* detach the CARLA server it spawns, so CARLA inherits the evaluator's
   process group and a ``killpg`` on the worker takes the simulator down with it. Detaching
   anything here reintroduces orphaned CARLA servers holding VRAM and ports.
2. **``--resume`` is omitted entirely.** The vendored evaluator declares it as
   ``type=bool``, so argparse applies ``bool()`` to the *string* and ``--resume=0`` evaluates
   ``bool("0")`` -> True. Every internal per-route script passes ``--resume=0`` and has
   therefore been running with in-file resume enabled; it is harmless there only because each
   XML holds one route and the checkpoint is unlinked before each attempt. We unlink the
   checkpoint too, and simply do not pass the flag.
3. **Runner-owned variables are exported LAST, and ``agent.env`` may not name one.** ``agent.env``
   is opaque, model-supplied config -- it is the whole mechanism by which a model's settings
   reach the agent without the runner containing model-specific code. Emitting it *after* the
   runner's own exports let a model config quietly win a fight it must never win: ``PORT`` or
   ``TM_PORT`` would put two workers on one simulator, ``CUDA_VISIBLE_DEVICES`` would unpin the
   GPU, and ``SEED`` / ``PYTHONHASHSEED`` would change the protocol seed per model while the
   result filename still said ``_seed42``. That is a determinism *and* an isolation hole, and
   every symptom of it is silent. Two independent defences, because either alone is one
   refactor away from being lost:

   * :data:`RESERVED_ENV` is rejected in ``agent.env`` at config load with a message naming the
     config field to use instead (see :func:`oodbench.config.build`); and
   * the ordering here puts ``agent.env`` *before* every runner-owned export, so even a
     reserved name that reached the script somehow would be overwritten rather than winning.
"""

from __future__ import annotations

import shlex
from pathlib import Path
from typing import TYPE_CHECKING, Dict, List

if TYPE_CHECKING:  # pragma: no cover
    from .config import Config, GpuSpec
    from .plan import RouteTask
    from .ports import PortPair

HEADER = """#!/bin/bash
# Generated by the OOD-PerceptionBench runner. Do not edit -- regenerated every run.
# route : {route}
# seed  : {seed}
# result: {result}
set -o pipefail
"""

#: Environment variables this module exports unconditionally. Every one of them is either a
#: worker-isolation control (ports, GPU), a determinism control (seed), or a path the runner
#: derives from validated config -- and every one of them has its own config surface. A value
#: for any of these coming from ``agent.env`` can only be a mistake, so it is an error rather
#: than something that silently wins or silently loses depending on emission order.
#:
#: Deliberately NOT reserved: ``PYTHONPATH`` and ``LD_LIBRARY_PATH``. The runner *composes*
#: those (it appends ``:"${VAR:-}"``), so an ``agent.env`` entry for either is additive rather
#: than a fight for control. Use ``agent.pythonpath`` / ``environment.ld_library_path_prepend``
#: when you want to control the ordering.
RESERVED_ENV: Dict[str, str] = {
    "CUDA_VISIBLE_DEVICES": "the `gpus:` list (`cuda` per entry)",
    "NVIDIA_VISIBLE_DEVICES": "the `gpus:` list (`cuda` per entry)",
    "GPU_RANK": "the `gpus:` list (`vulkan` per entry)",
    "CARLA_ROOT": "carla.root",
    "CARLA_SERVER": "carla.root",
    "WORK_DIR": "leaderboard.work_dir",
    "SCENARIO_RUNNER_ROOT": "leaderboard.scenario_runner_root",
    "LEADERBOARD_ROOT": "leaderboard.root",
    "ROUTES": "routes.root (the runner runs one route per attempt)",
    "TEAM_AGENT": "agent.entrypoint",
    "TEAM_CONFIG": "agent.config",
    "CHALLENGE_TRACK_CODENAME": "agent.track",
    "REPETITIONS": "benchmark.repetitions",
    "CHECKPOINT_ENDPOINT": "output.root",
    "SAVE_PATH": "output.root",
    "SEED": "benchmark.seed",
    "PYTHONHASHSEED": "benchmark.seed",
    "PORT": "ports.rpc_base / ports.stride",
    "TM_PORT": "ports.tm_base / ports.stride",
}


def _export(name: str, value: str) -> str:
    return f"export {name}={shlex.quote(str(value))}"


def render(task: "RouteTask", cfg: "Config", gpu: "GpuSpec", ports: "PortPair") -> str:
    """Return the bash source for one route attempt."""
    lb_root = Path(cfg.leaderboard["root"])
    sr_root = Path(cfg.leaderboard["scenario_runner_root"])
    work_dir = Path(cfg.leaderboard["work_dir"])
    carla_root = Path(cfg.carla["root"])
    evaluator = cfg.evaluator_path

    lines: List[str] = [HEADER.format(route=task.xml, seed=task.seed, result=task.result_path)]

    # ======================================================================================
    # USER-SUPPLIED SECTION. Everything below this block is runner-owned and overwrites it.
    # Order is load-bearing -- see property 3 in the module docstring.
    # ======================================================================================

    # -- user-supplied environment activation (conda / venv / module). Empty by default. ----
    if cfg.environment["activate"]:
        lines.append("# environment.activate")
        lines.extend(cfg.environment["activate"])
        lines.append("")

    # -- agent-specific environment, verbatim ----------------------------------------------
    # Emitted FIRST, not last: `environment.activate` may clobber it, so it goes after that,
    # but it must not be able to clobber the runner's ports, GPU pinning or seed. Reserved
    # names are already rejected at config load; this ordering is the second line of defence.
    if cfg.agent["env"]:
        lines.append("# agent.env (verbatim from the config; runner-owned variables follow "
                     "and win)")
        for k in sorted(cfg.agent["env"]):
            lines.append(_export(k, cfg.agent["env"][k]))
        lines.append("")

    # ======================================================================================
    # RUNNER-OWNED SECTION. Nothing above may override any of it.
    # ======================================================================================

    # -- GPU pinning: two independent indices, see DESIGN.md section 4 ----------------------
    lines.append("# GPU pinning: CUDA for the agent, Vulkan adapter for the CARLA server.")
    lines.append(_export("CUDA_VISIBLE_DEVICES", str(gpu.cuda)))
    lines.append(_export("NVIDIA_VISIBLE_DEVICES", str(gpu.cuda)))
    lines.append(_export("GPU_RANK", str(gpu.vulkan)))
    lines.append("")

    # -- LD_LIBRARY_PATH -------------------------------------------------------------------
    if cfg.environment["ld_library_path_prepend"]:
        joined = ":".join(cfg.environment["ld_library_path_prepend"])
        lines.append(f'export LD_LIBRARY_PATH={shlex.quote(joined)}:"${{LD_LIBRARY_PATH:-}}"')

    # -- CARLA / leaderboard roots ---------------------------------------------------------
    lines.append("# CARLA + leaderboard roots")
    lines.append(_export("CARLA_ROOT", str(carla_root)))
    lines.append('export CARLA_SERVER="${CARLA_ROOT}/CarlaUE4.sh"')
    lines.append(_export("WORK_DIR", str(work_dir)))
    lines.append(_export("SCENARIO_RUNNER_ROOT", str(sr_root)))
    lines.append(_export("LEADERBOARD_ROOT", str(lb_root)))

    pp_parts = list(cfg.agent["pythonpath"]) + [str(sr_root), str(lb_root),
                                                str(carla_root / "PythonAPI" / "carla")]
    quoted = ":".join(shlex.quote(p) for p in pp_parts)
    lines.append(f'export PYTHONPATH={quoted}:"${{PYTHONPATH:-}}"')
    lines.append("")

    # -- run parameters --------------------------------------------------------------------
    lines.append("# run parameters")
    lines.append(_export("ROUTES", str(task.xml)))
    lines.append(_export("TEAM_AGENT", str(cfg.agent["entrypoint"])))
    lines.append(_export("TEAM_CONFIG", str(cfg.agent["config"])))
    lines.append(_export("CHALLENGE_TRACK_CODENAME", str(cfg.agent["track"])))
    lines.append(_export("REPETITIONS", "1"))
    lines.append(_export("CHECKPOINT_ENDPOINT", str(task.result_path)))
    lines.append(_export("SAVE_PATH", str(task.agent_log_dir)))
    # Determinism: seed is a function of (route, repetition) only. Delivered three ways because
    # different agents read it differently. Never derived from the worker, GPU or port.
    lines.append(_export("SEED", str(task.seed)))
    lines.append(_export("PYTHONHASHSEED", str(task.seed)))
    lines.append(_export("PORT", str(ports.rpc)))
    lines.append(_export("TM_PORT", str(ports.tm)))
    lines.append("")

    record_flag = ""
    if cfg.output["record_carla"]:
        lines.append(f'mkdir -p {shlex.quote(str(task.carla_record_dir))}')
        record_flag = f" \\\n  --record={shlex.quote(str(task.carla_record_dir))}"

    lines.append('echo "[runner] host=$(hostname) rpc_port=${PORT} tm_port=${TM_PORT} '
                 'cuda=${CUDA_VISIBLE_DEVICES} vulkan_adapter=${GPU_RANK} seed=${SEED}"')
    if cfg.agent["working_dir"]:
        # Several published models must run from their own repository root.
        lines.append(f'cd {shlex.quote(str(cfg.agent["working_dir"]))} || exit 2')
    lines.append("")

    python = cfg.environment["python"]
    lines.append(
        f'{shlex.quote(python)} -u {shlex.quote(str(evaluator))} \\\n'
        f'  --routes="${{ROUTES}}" \\\n'
        f'  --repetitions="${{REPETITIONS}}" \\\n'
        f'  --track="${{CHALLENGE_TRACK_CODENAME}}" \\\n'
        f'  --checkpoint="${{CHECKPOINT_ENDPOINT}}" \\\n'
        f'  --agent="${{TEAM_AGENT}}" \\\n'
        f'  --agent-config="${{TEAM_CONFIG}}" \\\n'
        f'  --debug=0 \\\n'
        f'  --traffic-manager-seed="${{SEED}}" \\\n'
        f'  --port="${{PORT}}" \\\n'
        f'  --traffic-manager-port="${{TM_PORT}}" \\\n'
        f'  --timeout={float(cfg.carla["client_timeout_s"])} \\\n'
        f'  --gpu-rank="${{GPU_RANK}}"{record_flag}'
        # NOTE: --resume is deliberately NOT passed; see the module docstring.
    )
    lines.append("rc=$?")
    lines.append('echo "[runner] evaluator exited rc=${rc}"')
    lines.append("exit ${rc}")
    lines.append("")
    return "\n".join(lines)


def write(task: "RouteTask", cfg: "Config", gpu: "GpuSpec", ports: "PortPair") -> Path:
    task.mkdirs()
    path = task.job_script
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(task, cfg, gpu, ports), encoding="utf-8")
    path.chmod(0o750)
    return path
